### ISSUE TITLE
Provider Review

### ISSUE THREAD

**Issue by mbfrahry** [jdclouddevelopers/terraform-provider-jdcloud-archived#27]
Hello! My name is Matthew Frahry and I'm on the Terraform Ecosystem team at Hashicorp. I've been reviewing your provider and the provider looks great aside from a few glaring issues that need to be addressed. Below is an ordered list of that we can discuss further but I'd like to see addressed before we release it into our ecosystem. 

- [ ] It's not recommended setting anything other than Id in the create or update functions. [Here](https://github.com/jdclouddevelopers/terraform-provider-jdcloud/blob/master/jdcloud/resource_jdcloud_disk.go#L159) You're attempting to set these other attributes. It seems like what would be a better workflow would be to go from Create -> Update -> Read.  This is true for all resources. 

- [ ] The [Read function](https://github.com/jdclouddevelopers/terraform-provider-jdcloud/blob/master/jdcloud/resource_jdcloud_disk.go#L204)should set all of the attributes in the read function. Right now, you're only setting `name`, and `description`. This will affect your importability and those import tests will fail. This is true for all resources.

- [ ] Import support isn't being tested. You'll want to add the below test step as the last step for every test that has resource import support. (i.e. you'll add it to [disk_test.go](https://github.com/jdclouddevelopers/terraform-provider-jdcloud/blob/master/jdcloud/resource_jdcloud_disk_test.go#L40)) This is true for all resources.
```
{
	ResourceName:      resourceName,
	ImportState:       true,
	ImportStateVerify: true,
},

```

- [ ] [disk_test.go](https://github.com/jdclouddevelopers/terraform-provider-jdcloud/blob/master/jdcloud/resource_jdcloud_disk_test.go#L25) is missing testing for updating name and description. We prefer testing as much as we can to confirm functionality.  This is true for all resources. 

- [ ] [disk_id](https://github.com/jdclouddevelopers/terraform-provider-jdcloud/blob/master/website/docs/jdcloud_disk.html.markdown) doesn't exist in the schema but also in other resources `x_id` is the same as the id. Any resource with `x_id` can be removed in favor of just the id being referenced in the `Attributes Reference` section. 

- [ ] [waitForDisk](https://github.com/jdclouddevelopers/terraform-provider-jdcloud/blob/master/jdcloud/resource_jdcloud_disk.go#L282) has a similar helper function in the Terraform sdk called WaitForState(). The [aws provider](https://github.com/terraform-providers/terraform-provider-aws/blob/24e937a299c9115be47052404a97d6c9d5a4ccfa/aws/resource_aws_network_interface_attachment.go#L76) has a great example of what this looks like. 

- [ ] We're making the shift to moving to go modules as our vendoring tool in preparation for the release of 0.12. We're recommending all of our current and future providers to also make this shift. 

- [ ] [basic_test.go](https://github.com/jdclouddevelopers/terraform-provider-jdcloud/blob/master/jdcloud/basic_test.go) can be moved into [provider_test.go](https://github.com/jdclouddevelopers/terraform-provider-jdcloud/blob/master/jdcloud/provider_test.go)

- [ ] What is [jdcloud.test](https://github.com/jdclouddevelopers/terraform-provider-jdcloud/blob/master/jdcloud.test) If it's not needed for tests, can we remove it?

- [ ] [README.md](https://github.com/jdclouddevelopers/terraform-provider-jdcloud/blob/master/README.md) should be in the format of Requirements, Developing the Provider, Using the Provider, and Developing the Provider. It'll look very similar to the [aws readme](https://github.com/terraform-providers/terraform-provider-aws/blob/master/README.md)

- [ ] [Scanner](https://github.com/jdclouddevelopers/terraform-provider-jdcloud/tree/master/scanner) looks useful and solves a problem around Terraform and importing but I believe it should be moved out of the provider repo and into a separate repo. This is because there isn't a way for someone to actually use this tool after downloading the provider from the registry.  If anything, you can talk about the separate repo in your docs page. 

- [ ] The lack of tests around scanner also makes me hesitate around including it in in the provider.

**Comment by XiaohanLiang** [comment]
@mbfrahry Hello : )  Thank you for your patient in code review.  We will start fixing these problem, I believe it won't take too long

**Comment by XiaohanLiang** [comment]
@mbfrahry  Hello 👋 ! After days of working. I believe we have solved these problems , detailed updates contains :

1. **Workflow** : Usually goes from [`ResourceCreate` -> `ResourceRead`](https://github.com/jdclouddevelopers/terraform-provider-jdcloud/blob/master/jdcloud/resource_jdcloud_eip.go#L77) , under some specific scenario it goes  [`ResourceCreate` -> `ResourceUpdates`  -> `ResourceRead`](https://github.com/jdclouddevelopers/terraform-provider-jdcloud/blob/master/jdcloud/resource_jdcloud_disk.go#L229).

2. **ResourceRead** : `Read` function will set [all fields](https://github.com/jdclouddevelopers/terraform-provider-jdcloud/blob/master/jdcloud/resource_jdcloud_disk.go#L262) if applied, rather than one or two fields. Some fields, say `charge_duration` and `charge_unit` , which is not available from `ResourceRead` will not be set.

3. **TestCase** : Test cases for each resource has been added. For example, `Instance`. [Various test](https://github.com/jdclouddevelopers/terraform-provider-jdcloud/blob/master/jdcloud/resource_jdcloud_instance_test.go#L14) case has been introduced for `instance`. Tests around `System-Disk`,`Data-Disks` , `Image` ,`security-groups`, as well as their [**UpdateTest**](https://github.com/jdclouddevelopers/terraform-provider-jdcloud/blob/master/jdcloud/resource_jdcloud_instance_test.go#L113).

3. [**ImporterTest**](https://github.com/jdclouddevelopers/terraform-provider-jdcloud/blob/master/jdcloud/resource_jdcloud_eip_test.go#L48) : `ImporterTest` is introduced by adding a importer test step. `ImporterFunction` , unfortunately supports few resources, we plan to add more in the future.

4. **Website** : We have updated `x_id` into `id`

5. **WaitForXXX** : Thank you for introducing me `WaitForState` function. This function has been greatly implemented, clean, easy to use. We have update all [`waitForXXX` -> `WaitForState`](https://github.com/jdclouddevelopers/terraform-provider-jdcloud/blob/master/jdcloud/resource_jdcloud_disk.go#L99) ,cheers.

6. **Scanner** : Currently  we have removed `scanner` out of this project. This function is just a naive implementation. We are considering to make it an independent project in the future if necessary.

7. **GO1.12** : `GOMODULE` has been introduced. We've [replaced](https://github.com/jdclouddevelopers/terraform-provider-jdcloud/blob/master/go.mod#L14) some of them with local module since they're unavailable from internet. 

7. **Remaining Stuff**  : 
    - `README.md`  updated
    - `basic_test` moved into `provider_test`
    - `jdcloud_test` removed

If anything needed to be further modified, just let us know :)

**Comment by mbfrahry** [comment]
Hey @XiaohanLiang, thanks so much for taking the time to go over my review. Things are looking good for the changes you submitted and I believe we'll be ready to move this provider into our ecosystem once you've finished up the remaining minor pieces

**Comment by XiaohanLiang** [comment]
Hi, @mbfrahry . Sorry to ask but I'm not pretty sure. If the remaining pieces you've mentioned represents 

9. **Remaining Stuff**:
    - [`README.md`](https://github.com/jdclouddevelopers/terraform-provider-jdcloud/blob/master/README.md) updated
    - `basic_test` moved into [`provider_test`](https://github.com/jdclouddevelopers/terraform-provider-jdcloud/blob/master/jdcloud/provider_test.go)
    - `jdcloud_test` removed

I believe these problems have been fixed already. Sorry it can be my bad not state it clearly, or am I missing something? Thanks :)

**Comment by mbfrahry** [comment]
You're right! Thanks for the great work here. I'll close this issue and we can move forward. Thanks again @XiaohanLiang!
